extends Node
onready var Game = $".."
onready var PlayerShip = $"../WorldView/Viewport/World/PlayerShip"
onready var Asteroid1 = $"../WorldView/Viewport/World/Asteroid1"

var step = 0

func _process(delta):
	displayText()
	progress()

func displayText():
	$Label.text = currentText(step)

func progress():
	while isCompleted(step):
		step += 1
		$Timer.start(5)

func currentText(step: int) -> String:
	match step:
		1: return "The last civilization has died out millenia ago."
		2: return "You yourself have witnessed all of your dear ones pass."
		3: return "One by one. Until only you remained."
		4: return "Alone in the universe, gathering the very last things it has to offer."
		5: return "Your ship is powered by a black hole engine."
		6: return "It devours any kind of matter and spits out pure energy."
		7: return "You feed it asteroids, mostly."
		8: return "Look, there's one just here, in the bottom left corner of your screen!"
		9: return "Hover your cursor above it and quickly tap [space] to initiate a rotation."
		10: return "You can see that your cursor has changed to indicate that you aren't stationary."
		11: return "If you now hold space, your ship will reorient itself to face the asteroid."
		12: return "Just hover your cursor over the center of the asteroid and hold [space]."
		13: return "Press [W] to use your ion thruster to accelerate towards it."
		14: return "Press [S] to deaccelerate again. Beware, your forward-facing ion thrusters are weaker!"
		15: return "Once you're close to the asteroid, turn your stern (the back part of your ship) towards it."
		16: return "Try to get closer to the asteroid. Let the stern of your ship touch it."
		17: return "The mining equipment on your ship is energy-intensive, so before you turn on the drill..."
		18: return "First, increase the power generated by your BHE, found in the bottom centre of your ship."
		19: return "You can do this by a few clicks on the plus button on the BHE (bottom centre, right screen)."
		20: return "You've successfully set the target power. Now wait until the BHE meets it."
		21: return "Good! Now, you can turn on the drill in left wing of your ship."
		22: return "Click on the drill in the left part of the right screen."
		_: return ""

func isCompleted(step: int) -> bool:
	match step:
		9: return PlayerShip.a != 0
		12: return (
			PlayerShip.a == 0 and
			abs(PlayerShip.angleDiff(
				PlayerShip.dir.angle(),
				PlayerShip.angleToBody(Asteroid1)
			)) < 0.2
		)
		13: return (
			PlayerShip.position.direction_to(Asteroid1.position).dot(PlayerShip.v) > 5
		)
		16: return PlayerShip.drillable
		19: return Game.powerSupplyTarget == 100
		20: return Game.powerSupply == 100
		22: return Game.drillActive
		_:
			if step < 9 and isCompleted(9): return true
			if step < 12 and isCompleted(12): return true
			if step < 16 and isCompleted(16): return true
			if 16 < step and step < 19 and isCompleted(19): return true
			if 16 < step and step < 22 and isCompleted(22): return true
			
			return $Timer.time_left == 0
